### PR TITLE
Configuration files: keep unknown keys around

### PR DESCRIPTION
**Pull request by madebr**
Continuation of #261 

- Did some header fu in the tests directory.
  This reduces the compile time of the tests from 1m19s to 9s when touching GameConfig.hpp.
- Keep the unknown keys/data in memory and write them to string/file upon save

### CODE REVIEW

**Comment by JayFoxRox** [comment]
Hey, sorry for taking so long to get back to this. Do you still intend to work on this?
(I'll review this soon as it's long overdue, but I'm slightly worried my feedback would just be ignored if you don't have time to maintain this PR anymore..)

**Comment by madebr** [comment]
i will gladly incorporate any comments you have about these patches/config system in my PR.

**Comment by danhedron** [comment]
Running clang-format on ``GameConfig.cpp`` results in some changes, can you apply clang-format to the files changed in these commits?

**Comment by madebr** [comment]
clang-format applied

**Comment by danhedron** [comment]
LGTM

**Pull request merged**
