### PR TITLE
Temporary partial fix for duped cars & peds in first mission

### PR DESCRIPTION
**Pull request by husho**
Fixes duped cars and peds in first mission only if you skip cutscene. Watching whole intro movie still creates duplicates.

### CODE REVIEW

**Comment by dracc** [comment]
I've tested it and it seems to do the trick. Although I don't fancy hacks, this might be a good compromise until we find what actually causes it.

**Comment by darkf** [comment]
Instead of a hack I'd rather the real solution be implemented, unless it's super difficult.

**Comment by husho** [comment]
It's good enough for now, because duped cars are very annoying.

**Comment by husho** [comment]
Implementing controls system would take a while.

**Comment by JayFoxRox** [comment]
The entire function is a hack, so I'm fine with adding another temporary hack to fix an issue which might scare people away from openrw during the first minutes of trying it.

I did not test this myself, but will trust @husho .

LGTM.

*(I'd merge this, but will honor @darkf request for @danhedron review)*

**Pull request merged**
