### PR TITLE
renderer as shared ptr

### PR DESCRIPTION
**Pull request by ShFil119**
Actually render is causing memory leak.
Another option is to delete in destructor.

### CODE REVIEW

**Comment by danhedron** [comment]
The convention is to avoid manual allocation and deletion where possible, so this is the right track.

Does it need to use shared ptr? GameRenderer should be able to own the renderer outright with unique ptr.

**Comment by ShFil119** [comment]
Yes, pointer is also being kept in MapRenderer.

**Comment by paulsapps** [comment]
can't see why the ownership of the renderer is shared..

**Comment by ShFil119** [comment]
Ok, you probably thinking about unique passed with reference?
I'll prepare new commit and pull request. ;)

**Comment by JayFoxRox** [comment]
You can change commits and re-use this branch.. (instead of closing it)
Please avoid creating a new PR for changes as this discussion provides important background knowledge: Why did we choose unique_ptr over shared_ptr?

To make this easier, try to use more generic PR names such as "Renderer as smart-pointer" next time.

*(Opening a closed PR is tricky, so next time, just avoid closing it at all, unless you don't want to work on a new revision at all anymore)*

**Pull request closed without merging**
