### PR TITLE
[Ready] Fade fix part 2

### PR DESCRIPTION
**Pull request by husho**
- [x] Black screen in menu is still there (no idea what's the issue)
- [x] Load splash screen on save loading

### CODE REVIEW

**Comment by NFSMONSTR** [comment]
About black screen in menu:
In #470 you changed line
`if ((fadeTimer < world->state->fadeTime || !world->state->fadeOut) && !world->isPaused()) {`
to
`if ((fadeTimer <= world->state->fadeTime || !world->state->fadeOut) && !world->isPaused()) {`

In the main menu `fadeTimer == 0`,` world-> state->fadeTime == 0` and `!World->isPaused() == true`. So when you added `=` to this `if` this condition started to triggering in main menu

**Comment by husho** [comment]
Yeah, I know that, but alpha channel is set to 0 anyway, so why it's black?

**Comment by NFSMONSTR** [comment]
There is some possibility that gl_blend just disabled while this rendering. So I dont sure, but try to add `glEnable(GL_BLEND)` there

**Comment by husho** [comment]
I'll try, thanks.

**Comment by darkf** [comment]
Is this fixed & ready now?

**Comment by husho** [comment]
Yes

**Pull request merged**
