### PR TITLE
Various, small changes

### PR DESCRIPTION
**Pull request by ShFil119**
Small improvements. ;) 

- [x] fix appveyor
- [x] convert char[] to string

### CODE REVIEW

**Comment by dracc** [comment]
Is constexpr not available for std::string or why change the version strings into cstring and then cast them back into std::string?
Other than that it looks really nice! :+1:

**Comment by madebr** [comment]
A string cannot be constexpr as it allocates memory on the heap dynamically.

**Comment by danhedron** [comment]
Leave ``std::string`` as they are for now. Everything else seems like a step in the right direction.

**Comment by ShFil119** [comment]
Updated, I've removed constexpr from:
- ViewCamera defaultView (glm doesn't support constexpr for angleAxis)
- six other vectors which MSVC doesn't like

**Comment by darkf** [comment]
`sspaceRect` should be changed to use `std::array` in a future PR, but LGTM.

**Pull request merged**
