### PR TITLE
Increase tickrate to 60 times per second

### PR DESCRIPTION
**Pull request by ShFil119**
It should reduce level of perceptibility physics bugs and tearing non-interpolated objects.

### CODE REVIEW

**Comment by ShFil119** [comment]
Can you share how it looks like and your setup (hardware)?

**Comment by SonofUgly** [comment]
I was using rivatuner to limit the framerate, but I can't recreate it so either something else had changed or I was mistaken, so nevermind about that.

**Comment by dracc** [comment]
I tried it, albeit running with more or less constant 75fps.
Smooth as butter and car physics are suddenly manageable?
The Kumho didn't flip in the first corner at the end of the bridge and the Banshee only flips if you hit a curb at a bad angle.

**Comment by ShFil119** [comment]
Cars can still flop if one of wheels sinks in fender.
fender

**Pull request merged**
