### PR TITLE
Logger colourify

### PR DESCRIPTION
**Pull request by PerikiyoXD**
Let's add colours to our Console!

Just added some colours to the Logger output. Hope it's now a little bit better for your eyes!

### CODE REVIEW

**Comment by danhedron** [comment]
I'm not opposed to colour output, but getting colour output right in all terminals is quite difficult. I'd rather not start adding code to openrw for the esoteric art of figuring out if we should output colour or not.

This needs at least being able to turn off colour output with a command line switch, and making only output to the terminal coloured rather than all log listeners. Since some users might not want or be able to have colour output, and this is intended for output to a log file, where writing colour escape codes doesn't usually work.

**Comment by PerikiyoXD** [comment]
*sigh*

The nearest thing to a standard are ANSI escape codes. Blame MS because their system symbols are just dumb, not me because i want to add color...

**Comment by paulsapps** [comment]
https://github.com/paulsapps/alive/blob/dev/include/logger.hpp

This gets working colour output on osx/linux/windows

**Comment by JayFoxRox** [comment]
I'd rather like to see a small script to colorfy the output if necessary.
We have further debugging capabilities using the debug menu ingame + annotated GL traces.

Ideally we'd drop / get rid of most console output as we don't want / need it in the long term (except for unexpected situations, which should be very very rare).

**Pull request closed without merging**
