### PR TITLE
[Ready] Implemented some locate opcodes

### PR DESCRIPTION
**Pull request by dracc**
As written by @husho in #408

### CODE REVIEW

**Comment by dracc** [comment]
Placeholders for ScriptVec3, would that (if it's the third argument) be %3d% or %3o%?

**Comment by husho** [comment]
neither, o is for models and d is for numbers

**Comment by dracc** [comment]
That sounds sane. But what would be the right one?

**Comment by husho** [comment]
v2, v3? but then positions would misalign

**Comment by dracc** [comment]
@jayfoxrox clarified on irc that the placeholders are generated, so I will leave them be (mostly).

**Comment by dracc** [comment]
So, instead of "mostly", it would be preferable to not touch them at all?
What about the `@arg` lines, are those only related to OpenRW?
Great write-up, thank you @jayfoxrox!

**Pull request merged**
