### PR TITLE
New Screenshots and Improved direction in readme

### PR DESCRIPTION
**Pull request by danhedron**

### CODE REVIEW

**Comment by ShFil119** [comment]
Maybe screenshots should be taken from window with higher resolution? I think about aliasing.

**Comment by vflyson** [comment]
The first 2-3 screenshots seem to have an unusual (for the vanilla game) camera angle, I think they're perfect aside from that. In my opinion, it's important to make the good first impression for people who see this project for the first time, ergo making snapshots which would remind them of the original experience playing that game would describe better what the goal of OpenRW is.

**Comment by danhedron** [comment]
The UI is not scalled at the moment, so a larger window with result in weird UI. I can fudge it with super-sampling to reduce the aliasing or add a switch so UI rendering scales with the window.

**Comment by vflyson** [comment]
If it's not too much work I think it may be worth implementing that before taking snapshots for the updated README file; or taking the same snapshots in a 640x480 window and only scaling them down like 50% before uploading may also work, but you'd know better.

**Comment by ShFil119** [comment]
nit: maybe we should post also link to cdash?

**Comment by madebr** [comment]
https://github.com/danhedron/openrw/tree/update-readme
LGTM

**Pull request merged**
