### PR TITLE
Fix offset in GoTo()

### PR DESCRIPTION
**Pull request by mole99**
After a short discussion removing the offset in `setPosition()` is not the right way because the game expects to set the position of the feet, which results (or not) in the player falling through the ground.

This pull request doesn't fix the main problem, but adjusts the height in `GoTo()` which fixes the "jumping" and uses the correct values from the `btCapsuleShape().`

### CODE REVIEW

**Comment by husho** [comment]
For reference this is how game creates player:
```cpp
case CREATE_PLAYER:
   CRunningScript::CollectParameters(this, &this->m_nIp, 4);
    player_index.m_nIntValue = ScriptParams[0];
    printf("&&&&&&&&&&&&&Creating player: %d\n", ScriptParams[0].m_nIntValue);
    if (CStreaming::ms_aInfoForModel[0].status != STREAMING_AVAILABLE) {
        CStreaming::RequestSpecialModel(0, "player", STREAMING_KEEP|STREAMING_GAME_REQUIRED);
        CStreaming::LoadAllRequestedModels(0);
    }
    CPlayerPed::SetupPlayerPed(player_index.m_nIntValue);
    ped_pointer_offset.m_nIntValue = 316 * player_index.m_nIntValue;
    CWorld::Players[player_index.m_nIntValue].m_pPed->__parent.m_bReference = 2;
    CPlayerPed::DeactivatePlayerPed(player_index.m_nIntValue);
    x_from_script = ScriptParams[1].m_fFloatValue;
    y_from_script = ScriptParams[2].m_fFloatValue;
    z_from_script = ScriptParams[3].m_fFloatValue;
    if (ScriptParams[3].m_fFloatValue <= -100.0) {
        z_from_script = CWorld::FindGroundZForCoord(ScriptParams[1].m_fFloatValue, ScriptParams[2].m_fFloatValue);
    }
    dist = CEntity::GetDistanceFromCentreOfMassToBaseOfModel(&(*(&CWorld::Players[0].m_pPed + ped_pointer_offset.m_nIntValue))->__parent.__parent.__parent);
    player_ped = *(&CWorld::Players[0].m_pPed + ped_pointer_offset.m_nIntValue);
    z = dist + z_from_script;
    player_ped->__parent.__parent.__parent.__parent.__parent.pos.x = x_from_script;
    player_ped->__parent.__parent.__parent.__parent.__parent.pos.y = y_from_script;
    player_ped->__parent.__parent.__parent.__parent.__parent.pos.z = z;
    player_ped_1 = *(&CWorld::Players[0].m_pPed + ped_pointer_offset.m_nIntValue);
    player_pos.x = x_from_script;
    player_pos.z = z;
    player_pos.y = y_from_script;
    CTheScripts::ClearSpaceForMissionEntity(&player_pos, &player_ped_1->__parent.__parent.__parent);
    CPlayerPed::ReactivatePlayerPed(player_index.m_nIntValue);
    ScriptParams[0] = player_index;
    CRunningScript::StoreParameters(this_1, &this_1->m_nIp, 1);
```


```cpp
double __thiscall CEntity::GetDistanceFromCentreOfMassToBaseOfModel(CEntity *this) {
  return -CModelInfo::ms_modelInfoPtrs[this->m_nModelIndex]->m_pColModel->m_cBox.m_gBox.m_vecSup.z;
}
```

Script command suppose to give z coordinate at the level of the ground, and then script interpreter adjusts z coordinate to the center of ped's collision box.

**Comment by danhedron** [comment]
Thanks, that clears up what OpenRW is missing.

**Comment by husho** [comment]
> If I read this right, the original game stores the coordinates of the player relative to its center of mass? So OpenRW is doing this actually right?

Yeah

> Note: script::kSpawnOffset is 1.f, it should be half of the players collision box.

It should be done proper way like original game does

> The question is if opcode 0054 returns the characters center position, like it is currently done, or if the offset should be subtracted to get the position on the ground.

It returns center position

> And we don't have to fear that the script places the character in the ground, because then the offset is applied.

Correct

**Comment by danhedron** [comment]
@mole99 do you intend to implement the correct (or at least improved) opcode behaviour per the description above?

**Comment by mole99** [comment]
Yes, I would like to try to, but if I don't get it done today it can take a while, my holidays are starting tomorrow. But I don't think it's in a hurry, right?

**Pull request closed without merging**
