### PR TITLE
Some potential deference of null pointers

### PR DESCRIPTION
**Pull request by ShFil119**
It should increase stability a bit.
- [x] cleanup

### CODE REVIEW

**Comment by husho** [comment]
RW_CHECK presents only in debug builds and all it does is halt execution if conditions are met, not sure how it suppose to improve stability

**Comment by ShFil119** [comment]
I have expressed myself badly. :( Actually almost all de-referencing are checked in debug, except these ones. So it should help debug openrw easier.

**Comment by JayFoxRox** [comment]
Kind of pointless (I also dislike the `RW_CHECK` macro as I preffer `assert()` style conditions - but that's not your fault).

Otherwise LGTM (reviewed code, but did not test).

**Comment by darkf** [comment]
LGTM.

**Pull request merged**
