### PR TITLE
Remove screenshot functionality, as it's broken.

### PR DESCRIPTION
**Pull request by danhedron**

### CODE REVIEW

**Comment by christoph-heiss** [comment]
Is it because of the alignment issue?
This could be solved by `glPixelStorei(GL_UNPACK_ALIGNMENT, 1);`

Otherwise, what is broken?

**Comment by danhedron** [comment]
Yes; that is the issue. However there are plenty of ways to take a screenshot, using kscreenshot for example. I'd rather remove the path than try and beat these tools.

**Comment by JayFoxRox** [comment]
I guess there are a couple of reasons: Ugly pointer interface, lots of hardly used code ( #151 : there are better ways to take screenshots on all platforms) and the icing is the current alignment issue.

\- Unless GTA does it we don't have to replicate it and it shouldn't be our task to implement screenshotting which is to be expected on any recent OS.

Even if we need screenshots for the Camera in SA we can still recover this code in a couple of months when SA even partially works.
Eventually we'll have very different requirements and environment then though.

I appreciate this change.

---

Still compiles, game still works, F12 does nothing. Code also looks fine and grep doesn't find any mentions of "screenshot" either.

LGTM.

(We might have to change documentation after merging this)

**Comment by christoph-heiss** [comment]
Well, that's completely reasonable.

**Pull request merged**
