### PR TITLE
Miscellaneous macOS and rwviewer changes.

### PR DESCRIPTION
**Pull request by christoph-heiss**
Hi again!

Just some (I guess as usual you could say) some macOS-related stuff.
Maybe I get around sometime to do some hacking on the engine rather than just fixing build failures.

Anyway, a build-fixing commit, one for fixing DPI scaling in rwviewer and another fixing a rather minor inconvenient segfault.

I did not have the chance yet to test this changes on a linux box (although I do think nothing should have broken), so if someone could test that for me would be much appreciated! 

Thanks and with best regards!

### CODE REVIEW

**Comment by danhedron** [comment]
There's an existing failure with the latest Fedora. If macOS is able to build on Travis, could you swap fedora for that?

**Comment by christoph-heiss** [comment]
I pushed another commit to fix rwviewer-build on macOS and another to re-enable travis macOS builds as they seem to work fine (fixes #360).
Except one apparent segfault in "test_clump_clone", which I am going to have a look at (but this one is not really mission-critical I think).
`1: unknown location:0: fatal error: in "LoaderDFFTests/test_clump_clone": memory access violation at address: 0x00001420: no mapping at fault address
1: /Users/travis/build/rwengine/openrw/tests/test_LoaderDFF.cpp:66: last checkpoint`

But atleast with this we can know spot build regressions on macOS more easily and immediately.

And what do you mean with swapping fedora for it? I'm not quite sure. The fedora issue seems to be related to glm (probably #385 as well, I guess).

**Comment by ShFil119** [comment]
Yeah, fedora contains outdated version of glm. Error is triggered by gcc 7.3. Arch and ubuntu have newer packages with fixes.

**Comment by danhedron** [comment]
Looking into the failure, there's already a fix making its way through the fedora updates stream so it should go away within a few days.

**Comment by danhedron** [comment]
Everything seems to be working on my end.

**Comment by dracc** [comment]
What was the conclusion? Will the fedora build be swapped out in favor of a macos build, will a fourth build be added or is it status quo?

**Comment by christoph-heiss** [comment]
Since danhedron pointed out that the Fedora build should fix itself in a few days, with 5f97386 I (re-)added a forth build for macOS.

I think build-testing on a variety of Linux distros is a good idea to get full coverage.

**Pull request merged**
